# Generated by Django 2.2 on 2019-10-13 16:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="title")),
                ("image", models.URLField(verbose_name="image")),
                (
                    "description",
                    models.CharField(max_length=500, verbose_name="description"),
                ),
                ("datetime", models.DateTimeField(verbose_name="datetime")),
                (
                    "place_address",
                    models.CharField(max_length=50, verbose_name="place address"),
                ),
                ("place_map", models.URLField(verbose_name="place map")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
            ],
            options={"verbose_name": "event"},
        ),
        migrations.CreateModel(
            name="Invitation",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("message", models.CharField(max_length=100, verbose_name="message")),
                ("guests", models.PositiveSmallIntegerField(verbose_name="guests")),
                (
                    "confirmed",
                    models.BooleanField(default=False, verbose_name="confirmed"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="events.Event"
                    ),
                ),
            ],
            options={"verbose_name": "invitation"},
        ),
    ]
