# Generated by Django 2.2 on 2019-10-13 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("events", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.TextField(verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="invitation",
            name="message",
            field=models.TextField(verbose_name="message"),
        ),
    ]
