# Generated by Django 2.2 on 2019-10-13 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("events", "0002_auto_20191013_1712")]

    operations = [
        migrations.AddField(
            model_name="invitation",
            name="detail",
            field=models.TextField(default="", verbose_name="detail"),
            preserve_default=False,
        )
    ]
