version: '3'

services:
  postgres:
    image: postgres:11
    volumes:
      - ../postgres:/var/lib/postgresql/data
    env_file: ./.env

  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: ./.env
    volumes:
      - ./:/srv/www/
    working_dir: /srv/www
    command: python manage.py runserver_plus 0.0.0.0:8000
    depends_on:
      - postgres
    ports:
      - '8000:8000'
