name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: |
        cp env.example .env
        docker-compose build
    - name: Up postgres
      run: |
        docker-compose up -d postgres
    - name: Compile
      run: |
        docker-compose run --rm api python manage.py migrate
        docker-compose run --rm api python manage.py collectstatic
    - name: Test
      run: |
        docker-compose run --rm -e TEST=true api black --check .
